In [30]:
import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as matplot
from sklearn.model_selection import train_test_split
from sklearn import preprocessing, metrics
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

#Ejercicio 2

Se desea utilizar una red multiperceptrón para reconocer muestras de tres variedades diferentes de trigo: Kama, Rosa y Canadiense. Para entrenarla se utilizará una parte de los ejemplos del archivo Semillas.csv.

a) Con respecto a la arquitectura, indique:
* Cantidad de neuronas de la capa de entrada = 7
* Cantidad de neuronas de la capa de salida = 3
* Cantidad de pesos (arcos) que tiene la red si se utiliza una única capa oculta formada por 4 neuronas = (7+1) x 4 + (4+1) x 3 = 47 arcos

b) La arquitectura del multiperceptrón utilizado para predecir los 3 tipos de semillas está formada por 3 capas: la capa de entrada, una única capa oculta de 4 neuronas y la capa de salida. Las funciones de activación para las capas oculta y de salida son “tanh” y “sigmoid” respectivamente. Indique cuáles de los siguientes factores inciden en la dirección de cambio (signo de la modificación) de los pesos de la red:
* El error cometido en la predicción (*).
* El valor de la derivada de la función de activación.
* Los valores anteriores de los pesos de la red. (*)

c) Luego de ingresar una muestra de semilla a la red se obtiene como salida (0.78, 0, 0). Utilizando la arquitectura descripta en b), indique cuántos pesos de la red serán modificados sabiendo que la respuesta esperada es (1, 0, 0).

(7 + 1) x 4 + (4 + 1) = 8 x 4 + 5 = 32 + 5 = 37 arcos

In [31]:
# Load dataset
df_seeds = pd.read_csv('data/seeds.csv', delimiter=',')

In [32]:
# Numerization of class type
df_seeds.Clase = df_seeds.Clase.map({'Tipo1' : 0, 'Tipo2': 1, 'Tipo3' : 2})

In [33]:
# Normalization
for c in df_seeds.drop(columns=['Clase']).columns:
  min = df_seeds[c].min()
  range = df_seeds[c].max() - min
  df_seeds[c] = (df_seeds[c] - min) / range

In [34]:
# Split dataframe into train and test sets
train_set, test_set = train_test_split(df_seeds, test_size=0.2)

In [35]:
# examples
X = np.array(train_set.iloc[:, 0:-1])
# colum to predict
Y = np.array(train_set.iloc[:, 7:])

In [36]:
# Create the network architecture
model = Sequential()
model.add(Dense(4, input_shape=[7], activation='tanh'))
model.add(Dense(3, activation='sigmoid'))
model.compile(optimizer=SGD(lr=0.2), loss='mse', metrics='accuracy')

In [37]:
# Train the neural network
model.fit(X, keras.utils.to_categorical(Y), epochs=400, batch_size=20, verbose=0)

In [38]:
print("%% train accuracy : %.2f" % metrics.accuracy_score(
    Y,
    np.argmax(model.predict(X), axis=1))
)

6/6 [==============================] - 0s 662us/step
% train accuracy : 0.85


In [39]:
print("%% test accuracy : %.2f" % metrics.accuracy_score(
    np.array(test_set.iloc[:, 7:]),
    np.argmax(model.predict(np.array(test_set.iloc[:, 0:-1])), axis=1))
)

2/2 [==============================] - 0s 1ms/step
% test accuracy : 0.90


In [40]:
model.get_weights()

[array([[ 0.71277004,  0.05287476, -0.26324084, -0.3148361 ],
        [-0.5355592 , -0.5651818 ,  0.16952516,  0.5971799 ],
        [-0.54777163, -0.13584448,  0.04418944,  0.026851  ],
        [-0.5251185 , -0.04191753,  0.38227162,  0.37637413],
        [ 0.37321115, -0.41410768, -0.03513451,  0.6705159 ],
        [-0.40782398, -0.7523021 , -0.18568176, -0.8763938 ],
        [-0.4387616 ,  0.2988287 , -0.40000248,  0.59686   ]],
       dtype=float32),
 array([-0.07062533,  0.13429168,  0.22171572, -0.28396294], dtype=float32),
 array([[ 0.49350828,  0.27220246, -0.2540519 ],
        [ 0.73807013, -0.21661015,  0.35260484],
        [ 0.9139611 , -0.4365449 , -0.06256881],
        [ 0.01123755,  0.5929958 , -0.86748743]], dtype=float32),
 array([-0.01797733, -0.5828986 , -0.40101498], dtype=float32)]

In [41]:
#model.save('my_model.h5')